apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-server-deployment
  labels:
    app: student-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-server
  template:
    metadata:
      labels:
        app: student-server
    spec:
      containers:
        - name: student-server
          image: student-server:latest
          ports:
            - containerPort: 8080